---
gather_cities_task:
  description: Retrieve and validate a comprehensive list of European capitals and
    major touristic hubs to define {target_locations}. Use online directories and
    trusted geographic sources via {WebsiteSearchTool}. Ensure accuracy and relevance.
  expected_output: A validated list of cities representing European capitals and major
    touristic hubs, stored as {target_locations}.
  async_execution: false
  agent: data_collector
crawl_shops_task:
  description: For each city in {target_locations}, use {WebsiteSearchTool} to gather
    initial candidate shop URLs and preliminary data. Then, employ {ScrapeWebsiteTool}
    and {SeleniumScrapingTool} to extract detailed shop information including shop
    name, address, website, contact info, and social media links.
  expected_output: A dataset of candidate shops with extracted details, stored as
    {shop_data}.
  async_execution: false
  agent: shop_crawler
  context:
  - gather_cities_task
filter_shops_task:
  description: 'Analyze the collected {shop_data} and filter shops based on the following
    criteria: they must either sell high-end ready-to-wear products (chains priced
    between {price_chains} and wallets between {price_wallets} euros) or be categorized
    as lifestyle and stylish outdoor shops, and they must have an active social media
    presence. Use specific selection parameters to shortlist the best candidates.'
  expected_output: A refined list of shops meeting the criteria, stored as {filtered_shop_data}.
  async_execution: false
  agent: data_filter
  context:
  - crawl_shops_task
generate_report_task:
  description: 'Compile the {filtered_shop_data} into a comprehensive and well-organized
    final report. The report should include, for each shop: shop name, address, website,
    contact information, social media links, and the designated shop category (high-end
    ready-to-wear or lifestyle/outdoor). Integrate operations with the provided OpenAI
    API key {OPENAI_API_KEY} for any API-based processing.'
  expected_output: A finalized report with all required shop details, formatted and
    ready for review.
  async_execution: false
  agent: report_generator
  context:
  - filter_shops_task
